version: '3.7'
services:
  frontend:
    container_name: frontend
    image: 591105994502.dkr.ecr.ap-northeast-1.amazonaws.com/desk-tours-app-frontend:latest
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/frontend
    tty: true
  backend:
    container_name: backend
    image: 591105994502.dkr.ecr.ap-northeast-1.amazonaws.com/desk-tours-app-backend:latest
    build: ./server
    tty: true
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - ./server:/backend
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7.29
    restart: always
    ports:
      - '3306:3306'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --max_allowed_packet=128MB
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
